// This file is auto-generated by @hey-api/openapi-ts

export type app__models__data____variants____default__User = {
  id?: IdProperty_uuid_UUID__Input;
};

export type app__models__data__default__User_Input = {
  id: IdProperty_uuid_UUID__Input;
  email?: OptionalProperty_str_str_;
  full_name?: OptionalProperty_str_str_;
  is_superuser: boolean;
  identity: Identity_Input;
};

export type Collection_Item_ = {
  data: Array<Item_Output>;
  count: number;
};

export type Collection_User_ = {
  data: Array<User_Output>;
  count: number;
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type Identity_Input = {
  id: IdProperty_uuid_UUID__Input;
  created_at: string;
  modified_at: string;
  issuer: string;
  subject: string;
};

export type Identity_Output = {
  id: IdProperty_uuid_UUID__Output;
  created_at: string;
  modified_at: string;
  issuer: string;
  subject: string;
};

export type IdProperty_uuid_UUID__Input = string;

export type IdProperty_uuid_UUID__Output = string;

export type Item_Input = {
  id: IdProperty_uuid_UUID__Input;
  description?: OptionalProperty_str_str_;
  title?: OptionalProperty_str_str_;
  owner: app__models__data__default__User_Input;
};

export type Item_Output = {
  id: IdProperty_uuid_UUID__Output;
  description?: OptionalProperty_str_str_;
  title?: OptionalProperty_str_str_;
  owner: User_Output;
};

export type ItemUpdate = {
  id?: IdProperty_uuid_UUID__Input;
};

export type OptionalProperty_str_str_ = string | null;

export type User_Output = {
  id: IdProperty_uuid_UUID__Output;
  email?: OptionalProperty_str_str_;
  full_name?: OptionalProperty_str_str_;
  is_superuser: boolean;
  identity: Identity_Output;
};

export type UserUpdate = {
  id?: IdProperty_uuid_UUID__Input;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

export type ErrorPageData = {
  error: string;
};

export type ErrorPageResponse = unknown;

export type ItemsReadItemsData = {
  limit?: number;
  offset?: number;
};

export type ItemsReadItemsResponse = Collection_Item_;

export type ItemsCreateItemData = {
  requestBody: Item_Input;
};

export type ItemsCreateItemResponse = Item_Output;

export type ItemsReadItemData = {
  id: string;
};

export type ItemsReadItemResponse = Item_Output | null;

export type ItemsUpdateItemData = {
  id: string;
  requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = Item_Output;

export type ItemsDeleteItemData = {
  id: string;
};

export type ItemsDeleteItemResponse = void;

export type UsersReadUsersData = {
  limit?: number;
  offset?: number;
};

export type UsersReadUsersResponse = Collection_User_;

export type UsersCreateUserData = {
  requestBody: app__models__data__default__User_Input;
};

export type UsersCreateUserResponse = unknown;

export type UsersReadUserMeResponse = User_Output;

export type UsersDeleteUserMeResponse = void;

export type UsersUpdateUserMeData = {
  requestBody: UserUpdate;
};

export type UsersUpdateUserMeResponse = User_Output;

export type UsersReadUserByIdData = {
  userId: string;
};

export type UsersReadUserByIdResponse = unknown;

export type UsersUpdateUserData = {
  requestBody: app__models__data____variants____default__User;
  userId: string;
};

export type UsersUpdateUserResponse = User_Output;

export type UsersDeleteUserData = {
  userId: string;
};

export type UsersDeleteUserResponse = unknown;

export type UtilsHealthCheckResponse = boolean;
