// This file is auto-generated by @hey-api/openapi-ts

export type Collection_Item_ = {
    data: Array<Item>;
    count: number;
};

export type Collection_User_ = {
    data: Array<User_Output>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Identity = {
    id: IdProperty_uuid_UUID__Output;
    created_at?: string;
    modified_at: string;
    issuer: string;
    subject: string;
};

export type IdProperty_uuid_UUID__Input = string;

export type IdProperty_uuid_UUID__Output = string;

export type Item = {
    id: IdProperty_uuid_UUID__Output;
    description?: OptionalProperty_str_str_;
    title?: OptionalProperty_str_str_;
    owner: User_Output;
};

export type ItemCreate = {
    title?: (string | null);
    description?: (string | null);
};

export type ItemUpdate = {
    id?: IdProperty_uuid_UUID__Input;
};

export type OptionalProperty_str_str_ = string | null;

export type ResetPasswordBody = {
    reset_token: string;
    password: string;
};

export type SendPasswordResetBody = {
    email: string;
};

export type SignInBody = {
    email: string;
    password: string;
};

export type SignUpBody = {
    email: string;
    password: string;
};

export type User_Input = {
    id?: IdProperty_uuid_UUID__Input;
};

export type User_Output = {
    id: IdProperty_uuid_UUID__Output;
    email?: OptionalProperty_str_str_;
    full_name?: OptionalProperty_str_str_;
    is_superuser?: boolean;
    identity: Identity;
};

export type UserUpdate = {
    email?: (string | null);
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ErrorPageData = {
    error: string;
};

export type ErrorPageResponse = (unknown);

export type GelAuthGelAuthEmailPasswordSignUpData = {
    requestBody: SignUpBody;
};

export type GelAuthGelAuthEmailPasswordSignUpResponse = (unknown);

export type GelAuthGelAuthEmailPasswordSignInData = {
    requestBody: SignInBody;
};

export type GelAuthGelAuthEmailPasswordSignInResponse = (unknown);

export type GelAuthGelAuthEmailPasswordEmailVerificationData = {
    verificationToken: string;
};

export type GelAuthGelAuthEmailPasswordEmailVerificationResponse = (unknown);

export type GelAuthGelAuthEmailPasswordSendPasswordResetData = {
    requestBody: SendPasswordResetBody;
};

export type GelAuthGelAuthEmailPasswordSendPasswordResetResponse = (unknown);

export type GelAuthGelAuthEmailPasswordResetPasswordData = {
    requestBody: ResetPasswordBody;
};

export type GelAuthGelAuthEmailPasswordResetPasswordResponse = (unknown);

export type ItemsReadItemsData = {
    limit?: number;
    offset?: number;
};

export type ItemsReadItemsResponse = (Collection_Item_);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (Item);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = ((Item | null));

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (Item);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (void);

export type UsersReadUsersData = {
    limit?: number;
    offset?: number;
};

export type UsersReadUsersResponse = (Collection_User_);

export type UsersReadUserMeResponse = (User_Output);

export type UsersDeleteUserMeResponse = (void);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdate;
};

export type UsersUpdateUserMeResponse = (User_Output);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (unknown);

export type UsersUpdateUserData = {
    requestBody: User_Input;
    userId: string;
};

export type UsersUpdateUserResponse = (User_Output);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (unknown);

export type UtilsHealthCheckResponse = (boolean);