#! /usr/bin/env bash

set -e

cd backend
uv run \
  python -c "import app.main; import json; print(json.dumps(app.main.app.openapi()))" \
  > ../frontend/openapi.json
cd ../frontend
npm run generate-client
npm run format:fix ./src/client
